# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: lgalke/swiss

# title: "Mach. Learn. Commun. Lab."
title: "MLxC Lab"
tagline: "Decoding the Language of Machines" # Used by seo tag
description: >
  In the Machine Learning X Communication (MLxC) Lab at the University of Southern Denmark, we explore various topics in machine learning
  related to the theme of machine communication, such as language modeling, message-passing neural networks, neural
  communication, and communication in multi-agent systems.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mlxclab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: "" # the GitHub repo name for your project
github_username: mlxclab

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: mlxclab

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: black

# Build settings
markdown: kramdown

# Metadata for jekyll seo tag
author:
  name: "Lukas Galke"
  url: "https://lgalke.github.io"
  twitter: "LukasGalke"

# Plugins
plugins:
  - jekyll-seo-tag


# Collections

collections:
  team:
    order:
      - lukas-galke.md